### ISSUE TITLE
Chat Fragment - Search Field input Results Popup

### ISSUE THREAD

**Issue by Nattypat** [varunparbhakar/TheWeatherApp#15]
~As a developer, I need a place to implement the chat feature of the app.~

~I will add to the ChatList Fragment in Android Studio features consisting of:~
~- search field input (with a results popup)~

Proposing that search field will narrow the list of chats

**Comment by seburoh** [comment]
yes we talked about this it's dumb

**Comment by seburoh** [comment]
Closed
