### ISSUE TITLE
Contact Fragment - All Features implemented in Chat Fragment

### ISSUE THREAD

**Issue by Nattypat** [varunparbhakar/TheWeatherApp#17]
As a developer, I need a place to implement the contacts feature of the app.

I will implement all features from Chat Fragment into the Contacts Fragment in Android Studio consisting of:

~- search field input (with a results popup)~
~- add/new chat button~
- swipe left and right functionality (if doable, otherwise replace with buttons)

This should be tackled after chat fragment implements these features

**Comment by seburoh** [comment]
Currently missing:
-pushy integration
-start chat with contact
